inputSet:
  name: Build_kong_deployment_1685363525577-push-trigger-input-set
  identifier: Build_kong_deployment_1685363525577pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_kong_deployment_1685363525577
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
